{% set name = "SeqSero2" %}
{% set version = "1.0.2" %}
{% set sha256 = "6718ce5d30863771e54a4b7bd035079d79eb4aebe6a92842a378a893ef97bbc8" %}

package:
  name: '{{ name | lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/LSTUGA/seqsero2/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - blast >=2.2.28
    - biopython =1.73
    - samtools >=1.8
    - bedtools =2.17.0
    - sra-tools >=2.8.0
    - spades >=3.9.0
    - salmid =0.1.23
    - bwa >=0.7.12
test:
  commands:
    - SeqSero2_package.py -h
    - blastn -help
    - SalmID.py -h

about:
  home: https://github.com/denglab/{{ name }}
  license: GPLv2
  license_family: GPL
  license_file: 'LICENSE'
  summary: Salmonella serotype prediction from genome sequencing data
  dev_url: https://github.com/denglab/{{ name }}

extra:
  recipe-maintainers:
    - LSTUGA
  identifiers:
    - doi:10.1128/AEM.01746-19
